name: "\U0001F31F New hwid or license operation addition"
description: Submit a proposal/request to implement a new hwid or license operation
labels: [kind/feature, status/unconfirmed]
title: "[New HWID] "


body:
  - type: textarea
    id: description-request
    validations:
      required: true
    attributes:
      label: harkware identifier or license operation description
      description: |
        Put any and all important information relative to the new hwid or license operation here.

  - type: checkboxes
    attributes:
      label: Open source status
      description: |
          Please provide the open-source status, which would be very helpful
      options:
        - label: "The implementation is available"

  - type: textarea
    id: additional-info
    attributes:
      label: Provide useful links for the implementation
      description: |
        Please provide information regarding the implementation, and the authors.
        Please mention the authors by @gh-username if you're aware of their usernames.
